// Faculty Data
export const facultyMembers = [
  // ==================== PROGRAMMING & SOFTWARE DEVELOPMENT ====================
  {
    id: 1,
    name: "Muzammil Bilwani",
    designation: "Head of Software Development Faculty",
    qualification: "Senior Engineer at Careem | Bano Qabil Faculty Lead",
    experience: "10+ years in software development",
    expertise: [
      "Software Engineering",
      "System Design",
      "Backend Development",
      "Team Leadership",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Muzammil%20Bilwani.jpg",
    rating: 4.9,
    courses: [
      "Advanced Software Engineering",
      "System Design",
      "Backend Development",
    ],
    social: { linkedin: "https://www.linkedin.com/in/muzammilbilwani/" },
    department: "cs",
    achievements: [
      "Senior Engineer at Careem",
      "Head of Software Development at Bano Qabil",
      "Mentored 500+ developers",
    ],
  },
  {
    id: 2,
    name: "Muhammad Arsalan Sohail",
    designation: "Senior Mobile Development Instructor",
    qualification: "Senior Software Engineer at Eplanet Global",
    experience: "6+ years in mobile application development",
    expertise: [
      "Mobile App Development",
      "React Native",
      "iOS/Android",
      "Cross-platform Apps",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/arsalan-sohail.jpeg",
    rating: 4.8,
    courses: [
      "Mobile App Development",
      "React Native Mastery",
      "Cross-platform Development",
    ],
    social: {
      linkedin:
        "https://www.linkedin.com/in/muhammad-arsalan-sohail-3a9b96178/",
    },
    department: "mobile",
  },
  {
    id: 3,
    name: "Adil Ahmed Shekani",
    designation: "MERN Stack Lead Trainer",
    qualification: "Full Stack Web Development Specialist",
    experience: "3+ years teaching web development",
    expertise: ["MERN Stack", "React.js", "Node.js", "MongoDB", "Express.js"],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/adil.jpeg",
    rating: 4.7,
    courses: [
      "Full Stack Web Development",
      "MERN Stack Bootcamp",
      "React.js Fundamentals",
    ],
    social: { linkedin: "https://www.linkedin.com/in/adilahmedshekhani/" },
    department: "web",
  },
  {
    id: 4,
    name: "Abdul Basit Arif",
    designation: "Full Stack Engineer & Startup Mentor",
    qualification: "Full Stack Engineer, mentor, and startup founder",
    experience: "3+ years in IT | 6+ years in teaching and mentoring",
    expertise: [
      "Full Stack Development",
      "Startup Mentoring",
      "JavaScript",
      "Python",
    ],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Basit%20Arif.jpg",
    rating: 4.8,
    courses: [
      "Full Stack JavaScript",
      "Startup Development",
      "Project Management",
    ],
    social: {
      linkedin: "https://www.linkedin.com/in/abdul-basit-arif-b041a1254/",
    },
    department: "web",
  },
  {
    id: 5,
    name: "Abdul Munim Usmani",
    designation: "Software Engineer & CIT Instructor",
    qualification: "Software Engineer",
    experience: "Professional software engineer and teaching CIT",
    expertise: ["Software Engineering", "CIT", "Programming Fundamentals"],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/abdul_munim.jpg",
    rating: 4.6,
    courses: [
      "Computer Information Technology",
      "Programming Basics",
      "Software Engineering",
    ],
    social: { linkedin: "https://www.linkedin.com/in/abdul-munim1/" },
    department: "cs",
  },
  {
    id: 6,
    name: "Abdur Rehman Khan",
    designation: "Data Science Instructor",
    qualification: "Computer Scientist from UBIT-KU",
    experience: "Background in Python programming and Data Science",
    expertise: [
      "Python Programming",
      "Data Science",
      "Machine Learning",
      "Data Analysis",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Abdur%20Rehman%20Khan.jpg",
    rating: 4.7,
    courses: ["Python Programming", "Data Science Fundamentals", "CIT"],
    social: { linkedin: "https://www.linkedin.com/in/rehman-khan-179267263/" },
    department: "data",
  },
  {
    id: 7,
    name: "Ahmed Sarim",
    designation: "AI Engineer & CIT Instructor",
    qualification: "AI Engineer & final-year CS student at Iqra University",
    experience: "AI development and teaching",
    expertise: ["Artificial Intelligence", "Machine Learning", "Python", "CIT"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Ahmed%20Sarim.jpg",
    rating: 4.6,
    courses: ["AI Fundamentals", "Python for AI", "CIT"],
    social: { linkedin: "https://www.linkedin.com/in/ahmedsarim1161998/" },
    department: "ai",
  },
  {
    id: 8,
    name: "Muhammad Owais",
    designation: "Computer Science Instructor",
    qualification: "Bachelor in Computer Science",
    experience: "1.5 years of teaching experience",
    expertise: ["Computer Science", "Programming", "Teaching Methodology"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Mohammad%20Owais.jpg",
    rating: 4.5,
    courses: ["Computer Science Fundamentals", "Programming Basics"],
    social: { linkedin: "" },
    department: "cs",
  },
  {
    id: 9,
    name: "Alqama bin Shuja",
    designation: "Full Stack Developer",
    qualification: "Full Stack Developer",
    experience:
      "4 years of hands-on experience in designing scalable web applications",
    expertise: [
      "Full Stack Development",
      "Web Applications",
      "Scalable Systems",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Alqamah-1%20-%20Alqama%20Shuja.webp",
    rating: 4.7,
    courses: [
      "Full Stack Development",
      "Web Application Design",
      "Advanced JavaScript",
    ],
    social: { linkedin: "https://www.linkedin.com/in/alqama-shuja/" },
    department: "web",
  },
  {
    id: 10,
    name: "Amjad Aziz",
    designation: "Data Analytics Instructor",
    qualification: "IT & Data Analytics Specialist",
    experience:
      "Specializing in Data Analytics, Advanced Python, and Computer Networks",
    expertise: [
      "Data Analytics",
      "Advanced Python",
      "Computer Networks",
      "Excel",
    ],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Amjad%20Aziz.png",
    rating: 4.6,
    courses: ["Data Analytics", "Advanced Python", "Computer Networks"],
    social: { linkedin: "https://www.linkedin.com/in/amjad-aziz/" },
    department: "data",
  },
  {
    id: 11,
    name: "Basit Hussain",
    designation: "Full Stack JavaScript Developer",
    qualification: "Full-Stack JavaScript Developer",
    experience: "6+ years of professional experience",
    expertise: ["MERN Stack", "Next.js", "React", "UI/UX", "JavaScript"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Basit%20Hussain%20(1).jpeg",
    rating: 4.8,
    courses: ["MERN Stack Development", "Next.js", "Advanced React", "UI/UX"],
    social: { linkedin: "https://www.linkedin.com/in/basit-hussain-q/" },
    department: "web",
  },
  {
    id: 12,
    name: "Fahad bin Ashfaq",
    designation: "Software Engineer & AI Developer",
    qualification: "Software Engineer skilled in AI, Python, Java & Flutter",
    experience: "AI development, created banking system & AI bot",
    expertise: [
      "AI Development",
      "Python",
      "Java",
      "Flutter",
      "Banking Systems",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Fahad%20Bin%20ashfaq.jpg",
    rating: 4.7,
    courses: ["AI Development", "Python Programming", "Java", "Flutter"],
    social: { linkedin: "https://www.linkedin.com/in/fahad-bin-ashfaq07/" },
    department: "ai",
  },
  {
    id: 13,
    name: "Hasnain Ahmed",
    designation: "GenAI Engineer",
    qualification: "GenAI Engineer",
    experience: "Working on production grade AI agents for sales and support",
    expertise: [
      "Generative AI",
      "AI Agents",
      "Sales Automation",
      "Support Systems",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Hasnain%20Ahmed.jpg",
    rating: 4.7,
    courses: ["Generative AI", "AI Agents Development", "CIT"],
    social: {
      linkedin: "https://www.linkedin.com/in/hasnain-ahmed-579185242/",
    },
    department: "ai",
  },
  {
    id: 14,
    name: "Mirza Sarim Baig",
    designation: "MERN Stack Developer",
    qualification: "Certified MERN Stack developer with degree in CS",
    experience: "1+ year of industry experience",
    expertise: ["MERN Stack", "React.js", "Node.js", "MongoDB"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Sarim%20Baig.jpeg",
    rating: 4.6,
    courses: ["MERN Stack Development", "Web Development 1 & 2"],
    social: {
      linkedin: "https://www.linkedin.com/in/mirza-sarim-baig-20458a223/",
    },
    department: "web",
  },
  {
    id: 15,
    name: "Muhammad Muaaz",
    designation: "Data Analytics Instructor",
    qualification: "NED graduate and Data Analytics Expert",
    experience:
      "Skilled in Excel, Python, SQL, Power BI, and financial modeling",
    expertise: ["Excel", "Python", "SQL", "Power BI", "Financial Modeling"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Muhammad%20Muaaz.jpeg",
    rating: 4.7,
    courses: [
      "Data Analytics",
      "Excel Mastery",
      "Python for Data",
      "SQL",
      "Power BI",
    ],
    social: { linkedin: "https://www.linkedin.com/in/muhammed-muaaz/" },
    department: "data",
  },
  {
    id: 16,
    name: "Nadeem Ahmed",
    designation: "Cybersecurity Executive",
    qualification: "Senior Cybersecurity Executive",
    experience:
      "25+ years of sales & pre-sales experience in B2B cybersecurity",
    expertise: [
      "Cybersecurity",
      "B2B Sales",
      "Digital Solutions",
      "EMEA Markets",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Nadeem%20Ahmed.jpg",
    rating: 4.9,
    courses: [
      "Cybersecurity Fundamentals",
      "B2B Sales in Tech",
      "Digital Solutions",
    ],
    social: { linkedin: "https://www.linkedin.com/in/nadeem-ahmed-86300022/" },
    department: "cyber",
  },
  {
    id: 17,
    name: "Saqib Hussain",
    designation: "UI/UX Developer & Designer",
    qualification: "UI/UX Developer & Designer",
    experience: "Passionate about crafting user-centered digital experiences",
    expertise: ["UI/UX Design", "User-Centered Design", "Digital Experiences"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/saqib%20hussain.jpg",
    rating: 4.7,
    courses: ["UI/UX Design", "User Experience", "Digital Product Design"],
    social: { linkedin: "https://www.linkedin.com/in/saqib-hussain-755584ba/" },
    department: "design",
  },
  {
    id: 18,
    name: "Shahbaz Ahmed",
    designation: "MERN Stack Developer & Instructor",
    qualification: "MERN Stack Developer and Web Development Instructor",
    experience: "Helping students build real-world projects",
    expertise: ["MERN Stack", "Web Development", "Real-world Projects"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Shahbaz%20Ahmed.png",
    rating: 4.6,
    courses: ["MERN Stack Development", "Web Development", "Project Building"],
    social: { linkedin: "https://www.linkedin.com/in/shabaz-ahmed123/" },
    department: "web",
  },
  {
    id: 19,
    name: "Shahzaib Arshed",
    designation: "Google Certified UX Designer",
    qualification: "Google Certified UX Designer and Lecturer",
    experience: "Teaching at SMIU & Bano Qabil",
    expertise: [
      "UX Design",
      "UI Design",
      "Design Education",
      "Google Certified",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Shahzaib%20Arshed.jpg",
    rating: 4.8,
    courses: [
      "UX/UI Design",
      "Google Design Certification",
      "Design Fundamentals",
    ],
    social: { linkedin: "https://www.linkedin.com/in/shahzaibarshed/" },
    department: "design",
  },
  {
    id: 20,
    name: "Shaukat Sohail",
    designation: "Full Stack Developer",
    qualification: "Full Stack Developer",
    experience: "3+ years experience building web apps",
    expertise: ["Full Stack Development", "Python", "JavaScript", "Web Apps"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Shaukat%20Sohail.jpeg",
    rating: 4.6,
    courses: ["Full Stack Development", "Python", "JavaScript"],
    social: {
      linkedin: "https://www.linkedin.com/in/shaukat-sohail-012aaa167/",
    },
    department: "web",
  },
  {
    id: 21,
    name: "Syed Ibad Ali",
    designation: "Software Engineering Student",
    qualification: "Final-year Software Engineering student at NED University",
    experience: "Strong expertise in software development",
    expertise: ["Software Engineering", "Web Development", "Programming"],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Syed%20Ibad.webp",
    rating: 4.5,
    courses: ["Software Engineering Basics", "Web Development"],
    social: { linkedin: "https://www.linkedin.com/in/syed-ibad-developer/" },
    department: "cs",
  },
  {
    id: 22,
    name: "Syed Mahmood Ejaz",
    designation: "IT Instructor",
    qualification: "IT & Skills Development Professional",
    experience: "Teaching and connecting with learners",
    expertise: ["IT Training", "Skill Development", "Student Mentoring"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Mahmood%20ejaz.jpg",
    rating: 4.6,
    courses: ["IT Fundamentals", "Skill Development"],
    social: {
      linkedin: "https://www.linkedin.com/in/syed-mahmood-ejaz-a93910207/",
    },
    department: "cs",
  },
  {
    id: 23,
    name: "Syed Mustafa Raza",
    designation: "Cybersecurity Instructor",
    qualification: "BS CyberSecurity grad, Certified Pentester",
    experience: "Vulnerability Assessment Pentester",
    expertise: [
      "Cybersecurity",
      "Penetration Testing",
      "Vulnerability Assessment",
      "Python",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Syed%20Mustafa%20Raza.jpg",
    rating: 4.8,
    courses: ["CEH", "Cybersecurity Fundamentals", "Python for Security"],
    social: { linkedin: "https://linkedin.com/in/raza777" },
    department: "cyber",
  },
  {
    id: 24,
    name: "Waqar Rana",
    designation: "Software Engineer & Computer Teacher",
    qualification: "Software Engineer and Computer Teacher",
    experience:
      "3 years of industry experience and over 5 years of mentoring students",
    expertise: ["Full Stack Development", "Teaching Methodology", "Mentoring"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Waqar%20Ahmed.jpg",
    rating: 4.7,
    courses: ["Full Stack Development", "Computer Science", "Programming"],
    social: { linkedin: "https://www.linkedin.com/in/waqarranadev/" },
    department: "cs",
  },
  {
    id: 25,
    name: "Ali Haider",
    designation: "Full Stack Developer & Educator",
    qualification: "Experienced Full Stack Developer and Educator",
    experience:
      "5+ years of professional development experience and 6+ years in teaching",
    expertise: ["Full Stack Development", "Teaching", "JavaScript", "Python"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/ali%20-%20Ali%20Haider.jpg",
    rating: 4.8,
    courses: ["Full Stack Development", "JavaScript Mastery", "Python"],
    social: { linkedin: "https://www.linkedin.com/in/alihaiderdev/" },
    department: "web",
  },
  {
    id: 26,
    name: "Abdul Wasay",
    designation: "Full Stack Developer & IT Instructor",
    qualification: "Full Stack Software Developer and IT Instructor",
    experience: "Strong expertise in web development and teaching",
    expertise: ["PHP", "Laravel", "Frontend Development", "Web Development"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/abdul%20wasay.jpeg",
    rating: 4.7,
    courses: ["PHP & Laravel", "Full Stack Development", "Web Development"],
    social: {
      linkedin: "https://www.linkedin.com/in/syed-hafiz-abdul-wasay-b15929255/",
    },
    department: "web",
  },

  // ==================== E-COMMERCE FACULTY ====================
  {
    id: 27,
    name: "Abdul Hai Bhatti",
    designation: "Amazon Seller & E-commerce Expert",
    qualification: "Amazon seller, product research expert, and PPC specialist",
    experience: "Passionate about building brands and driving growth",
    expertise: ["Amazon Selling", "Product Research", "PPC", "Brand Building"],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Abdul%20Hai.jpg",
    rating: 4.7,
    courses: ["Amazon Selling", "E-commerce", "Product Research", "PPC"],
    social: { linkedin: "https://linkedin.com/in/abdulhaibhatti" },
    department: "ecommerce",
  },
  {
    id: 28,
    name: "Saad Azhar",
    designation: "Amazon Specialist & E-commerce Instructor",
    qualification: "Electrical Engineer and Amazon Specialist",
    experience: "Started Amazon career in 2020, trained 100+ students",
    expertise: ["Amazon Business", "E-commerce", "Product Launch"],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Saad%20Azher.png",
    rating: 4.6,
    courses: ["Amazon Business", "E-commerce Launch", "Product Management"],
    social: { linkedin: "" },
    department: "ecommerce",
  },
  {
    id: 29,
    name: "Sheikh Subhan Ahmed",
    designation: "E-commerce & Digital Marketing Trainer",
    qualification: "E-commerce & Digital Marketing Trainer",
    experience: "Helping launch & grow online businesses",
    expertise: ["E-commerce", "Digital Marketing", "Online Business Growth"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Subhan%20Ahmed.png",
    rating: 4.7,
    courses: ["E-commerce Development", "Digital Marketing", "Online Business"],
    social: { linkedin: "https://www.linkedin.com/in/subhanahmed0001/" },
    department: "ecommerce",
  },
  {
    id: 30,
    name: "Syed Muhammad Misbah ul Haque",
    designation: "E-commerce Development Instructor",
    qualification: "Front-end Developer",
    experience: "5 years of front-end development experience",
    expertise: [
      "E-commerce Development",
      "Frontend Development",
      "Web Development",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Syed%20Misbah.jpeg",
    rating: 4.7,
    courses: ["E-commerce Development", "Frontend Development"],
    social: { linkedin: "https://www.linkedin.com/in/syed-misbah-ul-haq/" },
    department: "ecommerce",
  },

  // ==================== E-MARKETING FACULTY ====================
  {
    id: 31,
    name: "Haris Mumtaz",
    designation: "Media & Marketing Professional",
    qualification: "Media & Marketing professional & mentor",
    experience: "7+ years in social media, production & anchoring",
    expertise: [
      "Social Media Marketing",
      "Media Production",
      "Anchoring",
      "Engagement Growth",
    ],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Haris%20Alam.jpg",
    rating: 4.8,
    courses: ["Social Media Marketing", "Media Production", "Content Strategy"],
    social: { linkedin: "https://www.linkedin.com/in/harisalam012/" },
    department: "marketing",
  },
  {
    id: 32,
    name: "Hassan Ahmed Zubairi",
    designation: "Digital Marketing Professional",
    qualification: "Digital Marketing Professional",
    experience:
      "4 years of experience, teaching since 1.0, trained over 1000 students",
    expertise: ["Digital Marketing", "Social Media", "Campaign Management"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Hassan%20Zuberi.jpeg",
    rating: 4.7,
    courses: [
      "Digital Marketing",
      "Social Media Strategy",
      "Campaign Management",
    ],
    social: { linkedin: "https://www.linkedin.com/in/hassan-zubairi/" },
    department: "marketing",
  },
  {
    id: 33,
    name: "Syeda Fiza Sajid",
    designation: "Digital Marketing Instructor",
    qualification:
      "Undergraduate Student of English Literature, Double Gold Medalist",
    experience: "Award-Winning Instructor, accomplished digital marketer",
    expertise: ["Digital Marketing", "Content Strategy", "Social Media"],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/fiza.JPG",
    rating: 4.7,
    courses: ["Digital Marketing", "Content Writing", "Social Media Strategy"],
    social: { linkedin: "https://www.linkedin.com/in/fiza-sajid-29227b2a6/" },
    department: "marketing",
  },
  {
    id: 34,
    name: "Aamrah Sami Khan",
    designation: "Content Writing Instructor",
    qualification:
      "Studied digital marketing and content writing from banoqabil",
    experience: "Now working as a content writing instructor",
    expertise: ["Content Writing", "Digital Marketing", "Copywriting"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Aamrah%20Khan.jpeg",
    rating: 4.6,
    courses: ["Content Writing", "Copywriting", "Digital Marketing Basics"],
    social: { linkedin: "https://www.linkedin.com/in/aamrah-khan/" },
    department: "marketing",
  },
  {
    id: 35,
    name: "Ayesha Kamran",
    designation: "Digital Marketing Instructor",
    qualification: "Bano Qabil Graduate and Social Media Manager",
    experience:
      "Started in Bano Qabil 1.0, gained hands-on experience managing social media",
    expertise: [
      "Digital Marketing",
      "Social Media Management",
      "Content Strategy",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Ayesha%20Kamran.jpg",
    rating: 4.6,
    courses: [
      "Digital Marketing",
      "Social Media Management",
      "Content Creation",
    ],
    social: { linkedin: "" },
    department: "marketing",
  },
  {
    id: 36,
    name: "Bisma Qureshi",
    designation: "Digital Marketing & Backend Developer",
    qualification:
      "IT undergraduate, backend developer, diploma in Digital Marketing IBA",
    experience: "Digital marketing, WordPress, metaAds, performance marketing",
    expertise: [
      "Digital Marketing",
      "Backend Development",
      "WordPress",
      "Meta Ads",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Bisma%20Qureshi.jpg",
    rating: 4.6,
    courses: [
      "Digital Marketing",
      "WordPress",
      "Meta Ads",
      "Performance Marketing",
    ],
    social: { linkedin: "https://linkedin.com/in/bismaqureshi" },
    department: "marketing",
  },
  {
    id: 37,
    name: "Erum Ghulam Hussain",
    designation: "Digital Marketing Trainer & SEO Specialist",
    qualification: "Educator, digital marketing trainer, and SEO specialist",
    experience:
      "Professional experience in teaching, content strategy, and SEO",
    expertise: ["Digital Marketing", "SEO", "Content Strategy", "Teaching"],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/erum.jpeg",
    rating: 4.7,
    courses: ["Digital Marketing", "SEO", "Content Strategy"],
    social: {
      linkedin: "https://www.linkedin.com/in/erum-ghulam-hussain-192a551b3/",
    },
    department: "marketing",
  },
  {
    id: 38,
    name: "Hoorain Salman",
    designation: "Performance Marketer & Content Creator",
    qualification:
      "2x Award-Winning Instructor | Performance Marketer | Content Creator",
    experience: "30+ brands scaled | 700+ students mentored",
    expertise: ["Performance Marketing", "Content Creation", "Brand Scaling"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Hoorain%20Salman.png",
    rating: 4.8,
    courses: ["Performance Marketing", "Content Creation", "Brand Growth"],
    social: {
      linkedin: "https://www.linkedin.com/in/hoorain-salman-ba0796249/",
    },
    department: "marketing",
    achievements: [
      "2x Award-Winning Instructor",
      "30+ brands scaled",
      "700+ students mentored",
    ],
  },
  {
    id: 39,
    name: "Ismail Ghazi",
    designation: "Tech Mentor & Marketing Instructor",
    qualification: "Bridging education and tech for 10+ years",
    experience: "From School Principal to Bano Qabil tech mentor",
    expertise: ["Marketing", "CIT", "Python", "Tech Education"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Ismail%20Ghazi.jpg",
    rating: 4.7,
    courses: ["Marketing", "CIT", "Python", "Tech Skills"],
    social: { linkedin: "https://www.linkedin.com/in/ismailghazi/" },
    department: "marketing",
  },
  {
    id: 40,
    name: "Layeba Ahsan",
    designation: "Digital Marketer & Meta Ads Expert",
    qualification: "Digital Marketer and freelancer",
    experience:
      "Meta ads expert, Google ads, YouTube ads campaign, graphic designer",
    expertise: [
      "Digital Marketing",
      "Meta Ads",
      "Google Ads",
      "YouTube Ads",
      "Graphic Design",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Layeba%20Aamir.jpg",
    rating: 4.6,
    courses: ["Meta Ads", "Google Ads", "YouTube Ads", "Graphic Design"],
    social: { linkedin: "https://linkedin.com/in/layeba-amir" },
    department: "marketing",
  },
  {
    id: 41,
    name: "Mahera Talib",
    designation: "Digital Marketing Strategist & Instructor",
    qualification:
      "Digital marketing strategist, instructor, and social media leader",
    experience: "National and international experience across UK, USA",
    expertise: [
      "Digital Marketing Strategy",
      "Social Media Leadership",
      "International Marketing",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Mahera%20Talib.jpg",
    rating: 4.8,
    courses: [
      "Digital Marketing Strategy",
      "Social Media Leadership",
      "International Marketing",
    ],
    social: { linkedin: "https://www.linkedin.com/in/mahera-talib-64752b268/" },
    department: "marketing",
  },
  {
    id: 42,
    name: "Muhammad Aazan Arain",
    designation: "Digital Marketing & Freelancing Instructor",
    qualification: "Digital Marketing & Freelancing Instructor",
    experience: "Trained and mentored students at Alkhidmat BanoQabil",
    expertise: ["Digital Marketing", "Freelancing", "Student Mentoring"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Muhammad%20Azzan%20Arain.jpg",
    rating: 4.6,
    courses: ["Digital Marketing", "Freelancing", "Online Business"],
    social: { linkedin: "https://linkedin.com/in/aazan17" },
    department: "marketing",
  },
  {
    id: 43,
    name: "Muhammad Arif",
    designation: "MBA Marketer & Design Instructor",
    qualification: "MBA marketer & Communication Design grad",
    experience: "15+ years at top brands",
    expertise: [
      "Digital Marketing",
      "Design",
      "Video Editing",
      "Brand Marketing",
    ],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Arif%20Ishaq.png",
    rating: 4.9,
    courses: ["Digital Marketing", "Design", "Video Editing", "Brand Strategy"],
    social: { linkedin: "https://www.linkedin.com/in/arif-ishaque/" },
    department: "marketing",
  },
  {
    id: 44,
    name: "Muhammad Yaminullah",
    designation: "Digital Marketer & SEO Expert",
    qualification: "Digital marketer, expert in SEO, social media marketing",
    experience: "Worked on various campaigns, teaching digital marketing",
    expertise: ["SEO", "Social Media Marketing", "Content Strategy"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Iyameen%20enayat.jpg",
    rating: 4.6,
    courses: ["SEO", "Social Media Marketing", "Content Strategy"],
    social: { linkedin: "" },
    department: "marketing",
  },
  {
    id: 45,
    name: "Muhammed Anas Arain",
    designation: "Digital Marketing Expert",
    qualification: "Digital marketing expert with 8 years in business growth",
    experience: "8 years business experience, 4 years teaching experience",
    expertise: [
      "Digital Marketing",
      "Business Growth",
      "WordPress",
      "Teaching",
    ],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/anas_arain.jpeg",
    rating: 4.7,
    courses: ["Digital Marketing", "WordPress", "Business Strategy"],
    social: {
      linkedin: "https://www.linkedin.com/in/muhammad-anas-arain-3babb9180/",
    },
    department: "marketing",
  },
  {
    id: 46,
    name: "SAIF Ahmed",
    designation: "Full Stack Digital Marketer",
    qualification: "IT Master's graduate & top-rated freelancer",
    experience: "Empowers students with skills in Full stack digital marketing",
    expertise: ["Full Stack Digital Marketing", "Freelancing", "IT Solutions"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Saif%20Ahmed.jpeg",
    rating: 4.7,
    courses: ["Full Stack Digital Marketing", "Freelancing", "Online Success"],
    social: { linkedin: "https://www.linkedin.com/in/saifahmedofficial/" },
    department: "marketing",
  },
  {
    id: 47,
    name: "Saim Fateh Malik",
    designation: "Creative Marketing Strategist & Trainer",
    qualification:
      "Creative marketing strategist & trainer with psychology background",
    experience:
      "Helping brands grow through emotional branding, storytelling & ads",
    expertise: [
      "Creative Marketing",
      "Emotional Branding",
      "Storytelling",
      "Advertising",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Saim%20Fateh%20Malik.jpeg",
    rating: 4.7,
    courses: ["Creative Marketing", "Brand Storytelling", "Advertising"],
    social: {
      linkedin: "https://www.linkedin.com/in/saim-fateh-malik-0bb409184/",
    },
    department: "marketing",
  },
  {
    id: 48,
    name: "Sameer Ali",
    designation: "Digital Marketing & Graphic Design Instructor",
    qualification: "Aspiring undergraduate pharmacy student",
    experience:
      "Keen interest and expertise in digital marketing and graphic design",
    expertise: ["Digital Marketing", "Graphic Design", "Content Creation"],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Sameer%20Ali.png",
    rating: 4.6,
    courses: ["Digital Marketing", "Graphic Design", "Content Creation"],
    social: { linkedin: "https://www.linkedin.com/in/sameeraliarain/" },
    department: "marketing",
  },
  {
    id: 49,
    name: "Ubaid ur Rehman Vohra",
    designation: "IT Trainer & Senior Faculty",
    qualification: "IT Trainer and Senior Faculty",
    experience:
      "Expertise in Digital Marketing, Software Engineering, and Project Coordination",
    expertise: [
      "Digital Marketing",
      "Software Engineering",
      "Project Coordination",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Ubaid%20Vohra.jpg",
    rating: 4.7,
    courses: [
      "Digital Marketing",
      "Software Engineering",
      "Project Management",
    ],
    social: { linkedin: "" },
    department: "marketing",
  },

  // ==================== GRAPHICS & VIDEO ANIMATION FACULTY ====================
  {
    id: 50,
    name: "Salman Saeed",
    designation: "IT & Multimedia Trainer",
    qualification: "Seasoned IT and Multimedia Trainer",
    experience: "24+ years of proven expertise in the creative industry",
    expertise: [
      "Multimedia",
      "Graphic Design",
      "Video Editing",
      "Animation",
      "Creative Industry",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Salman%20Saeed.jpg",
    rating: 4.9,
    courses: ["Multimedia", "Graphic Design", "Video Editing", "Animation"],
    social: { linkedin: "https://www.linkedin.com/in/salman-saeed-a446a121/" },
    department: "design",
  },
  {
    id: 51,
    name: "Muhammad Abdullah Waqar",
    designation: "Experience Designer",
    qualification: "Experience Designer in entertainment industry",
    experience: "Demonstrated history of working in entertainment industry",
    expertise: [
      "Animation",
      "Video Editing",
      "Graphic Design",
      "Experience Design",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Muhammad%20Abdullah%20Vaqar%20Siddiqui.jpg",
    rating: 4.7,
    courses: [
      "Animation",
      "Video Editing",
      "Graphic Design",
      "Experience Design",
    ],
    social: { linkedin: "https://www.linkedin.com/in/abbisid/" },
    department: "design",
  },
  {
    id: 52,
    name: "Muhammad Armughan Sarib",
    designation: "Graphic Design Instructor",
    qualification:
      "Graphic Design instructor with passion for design, communication, and marketing",
    experience: "Graphic design and communication",
    expertise: ["Graphic Design", "Communication Design", "Marketing"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Armughan%20Sarib.jpg",
    rating: 4.7,
    courses: [
      "Graphic Design",
      "Communication Design",
      "Marketing Integration",
    ],
    social: { linkedin: "https://linkedin.com/in/armughan-sarib-61811a174" },
    department: "design",
  },
  {
    id: 53,
    name: "Muhammad Fazal",
    designation: "Graphic Design Instructor",
    qualification:
      "Graphic Design Instructor and founder of Abdul Graphics Printing Agency",
    experience: "5+ years in design & printing",
    expertise: ["Graphic Design", "Printing", "Design"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Muhammad%20fazal.jpg",
    rating: 4.7,
    courses: ["Graphic Design", "Printing Technology", "Design Principles"],
    social: {
      linkedin: "https://www.linkedin.com/in/abdul-graphics-4371902a4/",
    },
    department: "design",
  },
  // Continuing with the remaining faculty members
  {
    id: 54,
    name: "Muhammad Mubasshir Lakhani",
    designation: "Graphic & Visual Design Instructor",
    qualification: "Graphic & Visual Design professional",
    experience:
      "Strong background in branding, social media graphics, and visual design",
    expertise: [
      "Graphic Design",
      "Visual Design",
      "Branding",
      "Social Media Graphics",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Mr.%20Mubasshir%20Lakhani.jpg",
    rating: 4.7,
    courses: [
      "Graphic Design",
      "Visual Design",
      "Brand Identity",
      "Social Media Graphics",
    ],
    social: { linkedin: "https://www.linkedin.com/in/mubasshirlakhani/" },
    department: "design",
  },
  {
    id: 55,
    name: "Muhammad Shahzad Shaikh",
    designation: "Multimedia Specialist",
    qualification: "Media Science graduate from Arena Multimedia",
    experience: "Specializes in graphics, video editing, 3D animation",
    expertise: ["Graphics", "Video Editing", "3D Animation", "Multimedia"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/shahzad%20shaikh.jpg",
    rating: 4.6,
    courses: ["Multimedia Design", "Video Editing", "3D Animation", "Graphics"],
    social: {
      linkedin: "https://www.linkedin.com/in/abdul-graphics-4371902a4/",
    },
    department: "design",
  },
  {
    id: 56,
    name: "Munawar Hassan",
    designation: "Graphic & Motion Designer",
    qualification: "Graphic & Motion Designer",
    experience: "4 years design experience, 3 years teaching experience",
    expertise: ["Graphic Design", "Motion Design", "Animation", "Teaching"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Munawar%20Hassan.JPG",
    rating: 4.6,
    courses: ["Graphic Design", "Motion Graphics", "Animation"],
    social: { linkedin: "https://www.linkedin.com/in/munawar-hassan112/" },
    department: "design",
  },
  {
    id: 57,
    name: "Rasheed Ahmed Khan",
    designation: "Graphic Design Instructor",
    qualification:
      "20+ years in advertising, ex-lead in national & multinational firms",
    experience: "Extensive experience in advertising industry",
    expertise: [
      "Graphic Design",
      "Advertising",
      "Brand Design",
      "Creative Direction",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Rasheed%20Ahmed%20Khan.jpg",
    rating: 4.8,
    courses: ["Graphic Design", "Advertising Design", "Brand Development"],
    social: { linkedin: "https://www.linkedin.com/in/rasheedahmedkhan/" },
    department: "design",
  },
  {
    id: 58,
    name: "Shujaat Ejaz",
    designation: "Graphic Designer & Web Designer",
    qualification:
      "Graphic Designer, Web Designer, and Social Media Marketing Expert",
    experience: "17+ years of professional experience",
    expertise: [
      "Graphic Design",
      "Web Design",
      "Social Media Marketing",
      "UI Design",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Shujaat%20Ejaz%20-%20SE%20Designer.png",
    rating: 4.7,
    courses: [
      "Graphic Design",
      "Web Design",
      "Social Media Marketing",
      "UI Design",
    ],
    social: { linkedin: "" },
    department: "design",
  },
  {
    id: 59,
    name: "Sumbul Mohammad Saleem",
    designation: "Multi-Skills Instructor",
    qualification:
      "Instructor in web development, Python, graphic design, and e-commerce",
    experience: "Focusing on hands-on, industry-relevant skills",
    expertise: ["Web Development", "Python", "Graphic Design", "E-commerce"],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Sumbul%20Mohammad%20saleem.jpg",
    rating: 4.6,
    courses: [
      "Web Development",
      "Python Programming",
      "Graphic Design",
      "E-commerce",
    ],
    social: { linkedin: "https://www.linkedin.com/in/sumbul-mohammad-saleem/" },
    department: "design",
  },
  {
    id: 60,
    name: "Syed Ayyaz Mustafa",
    designation: "Senior Graphic Designer & Instructor",
    qualification: "Senior Graphic Designer",
    experience:
      "22 years professional experience, 19 years teaching experience",
    expertise: [
      "Graphic Design",
      "Teaching",
      "Creative Direction",
      "Design Principles",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Syed%20Ayyaz%20Mustafa.jpg",
    rating: 4.8,
    courses: [
      "Graphic Design",
      "Advanced Design Principles",
      "Creative Direction",
    ],
    social: {
      linkedin: "https://www.linkedin.com/in/syed-ayyaz-mustafa-75b62034/",
    },
    department: "design",
  },
  {
    id: 61,
    name: "Talha Hassan",
    designation: "Director, Entrepreneur & Professor",
    qualification: "Director, Entrepreneur & Professor",
    experience: "17+ years experience, works with Fortune 500 firms",
    expertise: [
      "Creative Direction",
      "Entrepreneurship",
      "Mentoring",
      "Design Leadership",
    ],
    image:
      "https://ik.imagekit.io/banoqabil/BQ%20Instructors/Talha%20Hassan.JPG",
    rating: 4.9,
    courses: [
      "Creative Direction",
      "Design Entrepreneurship",
      "Professional Mentoring",
    ],
    social: { linkedin: "https://pk.linkedin.com/in/talhahassan116" },
    department: "design",
  },
  {
    id: 62,
    name: "Sheheryar Khan",
    designation: "Multimedia Faculty",
    qualification: "Computer Science graduate",
    experience: "Specializing in Graphic Design, Video Editing, and Animation",
    expertise: [
      "Graphic Design",
      "Video Editing",
      "Animation",
      "Computer Science",
    ],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/sheryar.jpeg",
    rating: 4.6,
    courses: ["Graphic Design", "Video Editing", "Animation", "Multimedia"],
    social: { linkedin: "" },
    department: "design",
  },
  {
    id: 63,
    name: "Syeda Javeria Shah",
    designation: "Graphic Design Instructor",
    qualification: "Passionate Graphic Design Instructor",
    experience: "5+ years of professional experience in creative industry",
    expertise: [
      "Graphic Design",
      "Creative Industry",
      "Design Principles",
      "Visual Communication",
    ],
    image: "https://ik.imagekit.io/banoqabil/BQ%20Instructors/javeria.jpeg",
    rating: 4.7,
    courses: ["Graphic Design", "Visual Communication", "Creative Design"],
    social: { linkedin: "https://www.linkedin.com/in/sumbul-mohammad-saleem/" },
    department: "design",
  },
];

// Campuses Data
export const campuses = [
  {
    id: 1,
    name: "AI Huda Campus (North Khi-Power House)",
    address: "North Karachi, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 2,
    name: "Anjuman Complex Campus (Sakhi Hasan)",
    address: "North Nazimabad, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 3,
    name: "Circle Social Welfare Foundation Campus (Gulshan-e-Iqbal)",
    address: "Gulshan-e-Iqbal 130, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 4,
    name: "AI-Aqsa Campus (Gulshan-e-Iqbal)",
    address: "Gulshan-e-Iqbal 130, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 5,
    name: "Clifton Campus",
    address: "Punjab Chowrangi, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 6,
    name: "Landhi#6 Campus (JI Office)",
    address: "Landhi # 6, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 7,
    name: "Liaquatabad Campus - (JI Office)",
    address: "Liaquatabad, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 8,
    name: "Escuela Schooling System (Bahadurabad)",
    address: "Bahadurabad, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 9,
    name: "Garden Campus",
    address: "Garden, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 10,
    name: "Gulberg Campus",
    address: "Gulberg, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 11,
    name: "Harmain School Campus (P.E.C.H.S-6)",
    address: "PECHS, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 12,
    name: "Idara Noor-e-Haq Campus",
    address: "Quaideen Colony, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 13,
    name: "Jamia Millia School Campus (Shah Faisal)",
    address: "Shahfaisal Town, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 14,
    name: "Jamia Tul Ansar Campus Moosa Lane",
    address: "Liyari, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 15,
    name: "Kausar Town Campus (Malir)",
    address: "Kausar Town Malir, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 16,
    name: "KMA Protech Institute, Kharadar",
    address: "Liyari, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 17,
    name: "Korangi Allah Wala Town Campus",
    address: "Korangi, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 18,
    name: "Orangi Town 11 ½ Campus",
    address: "Orangi Town, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 19,
    name: "Pakistan Central Homeopathic Medical College (Nazimabad)",
    address: "Nazimabad, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 20,
    name: "Piston College (Hub River Road)",
    address: "Baldia Town, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 21,
    name: "Safoora Campus",
    address: "Jauhar, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 22,
    name: "Shah Latif Town Campus",
    address: "Shah latif Town, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 23,
    name: "Umer-e-Farooq Masjid (PIA Society)",
    address: "Jauhar, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 24,
    name: "Etawa Campus (Gulshan-e-Maymar)",
    address: "Gulshan-e-Maymar, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 25,
    name: "HOL Kara Bai Campus (Lyari)",
    address: "Liyari, Karachi",
    image:
    "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 26,
    name: "Bahria Town Campus",
    address: "Bahria Town, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 27,
    name: "Gulshan-e-Hadeed Campus",
    address: "Gulshan-e-Hadeed, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 28,
    name: "Askari Degree College (Bahadurabad)",
    address: "Bahadurabad, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 29,
    name: "Dr. Mehmood Hussain Campus (Shahfaisal Town)",
    address: "Shahfaisal Town, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 30,
    name: "Sherwani Suites Campus",
    address: "Gulshan-e-Maymar, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 31,
    name: "Metroville Campus",
    address: "SITE Area, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
  {
    id: 32,
    name: "SKIT - Keamari Campus",
    address: "Keamari, Karachi",
    image:
      "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    phone: "+92 317-8226242",
    email: "banoqabil.khi@alkhidmat.com",
    facilities: ["Modern Computer Labs", "Projector", "Wi-Fi"],
  },
];

// News Data
export const newsArticles = [
  {
    id: 1,
    title: "BanoQabil Wins Best IT Education Award 2025",
    excerpt:
      "Recognized for excellence in IT education and student success stories",
    content: "Full content here...",
    category: "Achievements",
    date: "2025-07-15",
    author: "Admin",
    image:
      "https://banoqabil.org/org_images/program_4.png",
    tags: ["Award", "Recognition", "Education"],
    featured: true,
  },
  {
    id: 2,
    title: "New AI & Machine Learning Course Launch",
    excerpt: "Introducing our comprehensive AI course with industry experts",
    content: "Full content here...",
    category: "Courses",
    date: "2024-01-10",
    author: "Dr. Ali Hassan",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    tags: ["AI", "New Course", "Technology"],
    featured: true,
  },
  {
    id: 3,
    title: "Bano Qabil Graduation Ceremony 3.0!",
    excerpt: "Celebrating excellence as hundreds of graduates receive their certificates and step into promising tech careers",
    content: "Full content here...",
    category: "Achievements",
    date: "June 21, 2025",
    author: "Management",
    image:
      "https://website-assests-v2.s3.us-east-1.amazonaws.com/news/girlsconvocation.jpg",
    tags: ["BanoQabilGraduation", "TechCareers", "SYouthEmpowerment"],
    featured: false,
  },
  {
    id: 4,
    title: "MoU Signing Ceremony with Fossphorus",
    excerpt: "Strategic partnership established for Satellite Incubation Center to provide youth with hands-on industry experience and advanced learning opportunities",
    content: "Full content here...",
    category: "Partnerships",
    date: "May 13, 2025",
    author: "Partnership Team",
    image:
      "https://website-assests-v2.s3.us-east-1.amazonaws.com/news/mou.jpg",
    tags: ["MoUSigning", "StrategicPartnership", "SatelliteIncubationCenter"],
    featured: false,
  },
  {
    id: 5,
    title: "Strategic MoU with CEGA for Gaming & Animation",
    excerpt: "Empowering youth and supporting startups to position Pakistan as a regional hub for creative technology in gaming and animation sectors",
    content: "Full content here...",
    category: "Partnerships",
    date: "December 3, 2025",
    author: "Partnership Team",
    image:
      "https://website-assests-v2.s3.us-east-1.amazonaws.com/news/cega.jpg",
    tags: ["StrategicMoU", "GamingAndAnimation", "YouthEmpowerment"],
    featured: false,
  },
  {
    id: 6,
    title: "BanoQabil Nexus Summit 2025 – Certificate Distribution Ceremony",
    excerpt: "Distinguished industry leaders and experts honored emerging innovators and entrepreneurs at our Incubation Center's prestigious certification event",
    content: "Full content here...",
    category: "Events",
    date: "October 26, 2025",
    author: "Events Team",
    image:
      "https://website-assests-v2.s3.us-east-1.amazonaws.com/news/nexus.jpg",
    tags: ["BanoQabilNexusSummit", "InnovationAndEntrepreneurship", "IncubationCenter"],
    featured: false,
  },
];

// Careers Data
export const jobOpenings = [
  {
    id: 1,
    title: "Senior Web Development Instructor",
    department: "Academics",
    location: "Karachi",
    type: "Full-time",
    experience: "5+ years",
    salary: "Competitive",
    description: "Looking for experienced web development instructor...",
    requirements: [
      "5+ years of web development experience",
      "Expertise in MERN stack",
      "Teaching experience preferred",
      "Excellent communication skills",
    ],
    postedDate: "2024-01-15",
    deadline: "2024-02-15",
    urgent: true,
  },
  {
    id: 2,
    title: "Admissions Counselor",
    department: "Administration",
    location: "Lahore",
    type: "Full-time",
    experience: "2+ years",
    salary: "Market Competitive",
    description: "Responsible for student admissions and counseling...",
    requirements: [
      "Bachelor's degree in any field",
      "2+ years in counseling or sales",
      "Excellent interpersonal skills",
      "Target-oriented approach",
    ],
    postedDate: "2024-01-10",
    deadline: "2024-02-10",
    urgent: true,
  },
  {
    id: 3,
    title: "UI/UX Design Instructor",
    department: "Academics",
    location: "Islamabad",
    type: "Part-time",
    experience: "3+ years",
    salary: "Negotiable",
    description: "Part-time instructor for UI/UX design courses...",
    requirements: [
      "3+ years UI/UX design experience",
      "Proficiency in Figma and Adobe Suite",
      "Portfolio required",
      "Teaching experience a plus",
    ],
    postedDate: "2024-01-05",
    deadline: "2024-01-31",
    urgent: false,
  },
  {
    id: 4,
    title: "IT Support Specialist",
    department: "IT Department",
    location: "Karachi",
    type: "Full-time",
    experience: "2+ years",
    salary: "Market Competitive",
    description: "Provide technical support for campus infrastructure...",
    requirements: [
      "Diploma/Degree in IT",
      "2+ years IT support experience",
      "Networking knowledge",
      "Problem-solving skills",
    ],
    postedDate: "2024-01-01",
    deadline: "2024-01-25",
    urgent: false,
  },
  {
    id: 5,
    title: "Content Writer (Technical)",
    department: "Marketing",
    location: "Remote",
    type: "Contract",
    experience: "2+ years",
    salary: "Per Project",
    description: "Create technical content for courses and marketing...",
    requirements: [
      "Technical writing experience",
      "Understanding of IT concepts",
      "Excellent English writing skills",
      "Portfolio required",
    ],
    postedDate: "2023-12-28",
    deadline: "2024-01-20",
    urgent: false,
  },
  {
    id: 6,
    title: "Campus Coordinator",
    department: "Administration",
    location: "Hyderabad",
    type: "Full-time",
    experience: "3+ years",
    salary: "Market Competitive",
    description: "Manage campus operations and student services...",
    requirements: [
      "3+ years administrative experience",
      "Management skills",
      "Student handling experience",
      "Multitasking ability",
    ],
    postedDate: "2023-12-25",
    deadline: "2024-01-15",
    urgent: false,
  },
];

export const benefits = [
  "Competitive Salary Packages",
  "Health Insurance",
  "Professional Development Allowance",
  "Flexible Working Hours",
  "Performance Bonuses",
  "Paid Time Off",
  "Training Opportunities",
  "Friendly Work Environment",
];
